services:
  database:
    image: mongo:latest
    container_name: database_container
    ports:
      - 27017:27017
    command: ["mongod", "--replSet", "rs0"]
    networks:
      - backend_network
    volumes:
      - database_volume:/data/db
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - 6379:6379
    networks:
      - backend_network
    volumes:
      - redis_volume:/data
  server:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: server_container
    ports:
      - 5000:5000
    networks:
      - backend_network
    volumes:
      - "./:/usr/src/app"
    depends_on:
      - database
      - redis
networks:
  backend_network:
    driver: bridge
volumes:
  database_volume:
  redis_volume:
